server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1300421975a
    url: jdbc:mysql://localhost:3306/tdesign?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.design.entity

myfile:
  accessPath: /uploadimg/
  staticAccessPath: /uploadimg/**
#  uploadFolder: /root/uploadFiles/
  uploadFolder: C://File_rec/tmp/

#  # 上传的服务器上的映射文件夹
#  file.accessPath=/uploadimg/
#  #静态资源对外暴露的访问路径
#  file.staticAccessPath=/uploadimg/**
#  #文件上传目录（注意Linux和Windows上的目录结构不同）
#  #file.uploadFolder=/root/uploadFiles/
#  file.uploadFolder=C://File_rec/tmp/